#Ex1
print("Exercise 1")
print("a)")
print("D is 'fishes'")
print("P is 'need water to survive'")
print("Formal form: For all x in D,P(x)")
print("b)")
print("D is 'person'")
print("P is 'left hand'")
print("Formal form: For all x in D,P(x)")
print("c)")
print("D is 'employee in the company'")
print("P is 'late to work everyday'")
print("Formal form: For all x in D,P(x)")
print("d)")
print("D is 'fished in this pond'")
print("P is 'are Koi fish'")
print("Formal form: For all x in D,P(x)")
